export const TRUSTLEDGER_ABI = [
	{
		inputs: [{ internalType: "address", name: "arbitration_", type: "address" }],
		stateMutability: "nonpayable",
		type: "constructor",
	},
	{ inputs: [], name: "AlreadySet", type: "error" },
	{ inputs: [], name: "CompletionPctOutOfRange", type: "error" },
	{ inputs: [], name: "ContractNotFinished", type: "error" },
	{ inputs: [], name: "DeadlineElapsed", type: "error" },
	{ inputs: [], name: "DeadlineNotElapsed", type: "error" },
	{ inputs: [], name: "EmptyHash", type: "error" },
	{ inputs: [], name: "EmptyURI", type: "error" },
	{ inputs: [], name: "EnforcedPause", type: "error" },
	{ inputs: [], name: "EthTransferFailed", type: "error" },
	{ inputs: [], name: "ExpectedPause", type: "error" },
	{ inputs: [], name: "InsufficientFunds", type: "error" },
	{ inputs: [], name: "InvalidAcceptanceWindow", type: "error" },
	{ inputs: [], name: "InvalidArbitrationFee", type: "error" },
	{ inputs: [], name: "InvalidBufferFactor", type: "error" },
	{ inputs: [], name: "InvalidHoldBack", type: "error" },
	{ inputs: [], name: "InvalidPreviousContract", type: "error" },
	{ inputs: [], name: "InvalidSignature", type: "error" },
	{
		inputs: [{ internalType: "enum TrustLedger.Status", name: "current", type: "uint8" }],
		name: "InvalidStatus",
		type: "error",
	},
	{ inputs: [], name: "InvalidTokenParams", type: "error" },
	{ inputs: [], name: "InvalidWarrantyPeriod", type: "error" },
	{ inputs: [], name: "NotPauser", type: "error" },
	{ inputs: [], name: "RatingAlreadySubmitted", type: "error" },
	{ inputs: [], name: "RatingOutOfRange", type: "error" },
	{ inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
	{ inputs: [], name: "SelfContract", type: "error" },
	{ inputs: [], name: "TokenTransferFailed", type: "error" },
	{ inputs: [], name: "Unauthorized", type: "error" },
	{ inputs: [], name: "WindowElapsed", type: "error" },
	{ inputs: [], name: "WindowNotElapsed", type: "error" },
	{ inputs: [], name: "ZeroAddress", type: "error" },
	{
		anonymous: false,
		inputs: [{ indexed: true, internalType: "uint256", name: "id", type: "uint256" }],
		name: "ContractAccepted",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "uint256", name: "newId", type: "uint256" },
			{ indexed: true, internalType: "uint256", name: "previousId", type: "uint256" },
		],
		name: "ContractAmended",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [{ indexed: true, internalType: "uint256", name: "id", type: "uint256" }],
		name: "ContractCancelled",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "uint256", name: "id", type: "uint256" },
			{ indexed: true, internalType: "address", name: "client", type: "address" },
			{ indexed: true, internalType: "address", name: "freelancer", type: "address" },
			{ indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
		],
		name: "ContractCreated",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [{ indexed: true, internalType: "uint256", name: "id", type: "uint256" }],
		name: "ContractRejected",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "uint256", name: "id", type: "uint256" },
			{ indexed: true, internalType: "address", name: "to", type: "address" },
			{ indexed: true, internalType: "uint256", name: "amount", type: "uint256" },
		],
		name: "FundsReleased",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [{ indexed: false, internalType: "address", name: "account", type: "address" }],
		name: "Paused",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "uint256", name: "id", type: "uint256" },
			{ indexed: true, internalType: "bytes32", name: "powHash", type: "bytes32" },
			{ indexed: false, internalType: "string", name: "powURI", type: "string" },
		],
		name: "ProofSubmitted",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "uint256", name: "id", type: "uint256" },
			{ indexed: true, internalType: "address", name: "rater", type: "address" },
			{ indexed: false, internalType: "uint8", name: "score", type: "uint8" },
		],
		name: "RatingSubmitted",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "uint256", name: "id", type: "uint256" },
			{ indexed: true, internalType: "uint256", name: "completionPct", type: "uint256" },
		],
		name: "RulingExecuted",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [{ indexed: false, internalType: "address", name: "account", type: "address" }],
		name: "Unpaused",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "uint256", name: "id", type: "uint256" },
			{ indexed: true, internalType: "address", name: "freelancer", type: "address" },
			{ indexed: true, internalType: "uint256", name: "amount", type: "uint256" },
		],
		name: "WarrantyFundsClaimed",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [{ indexed: true, internalType: "uint256", name: "id", type: "uint256" }],
		name: "WorkApproved",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "uint256", name: "id", type: "uint256" },
			{ indexed: true, internalType: "uint256", name: "arbitrationId", type: "uint256" },
		],
		name: "WorkDisputed",
		type: "event",
	},
	{
		inputs: [],
		name: "ARBITRATION",
		outputs: [{ internalType: "contract IArbitration", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "BPS_DENOMINATOR",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "MAX_ARBITRATION_FEE_BPS",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "MAX_HOLD_BACK_BPS",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "MIN_ACCEPTANCE_WINDOW",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "MIN_BUFFER_FACTOR",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "MIN_HOLD_BACK_BPS",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "uint256", name: "id", type: "uint256" },
			{ internalType: "uint8", name: "v", type: "uint8" },
			{ internalType: "bytes32", name: "r", type: "bytes32" },
			{ internalType: "bytes32", name: "s", type: "bytes32" },
		],
		name: "acceptContract",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
		name: "approveWork",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
		name: "cancelPending",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
		name: "claimAfterAcceptanceWindow",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
		name: "claimAfterDeadlineMiss",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
		name: "claimWarrantyFunds",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "freelancer", type: "address" },
			{ internalType: "bytes32", name: "contractHash", type: "bytes32" },
			{ internalType: "string", name: "contractURI", type: "string" },
			{ internalType: "uint256", name: "estimatedDuration", type: "uint256" },
			{ internalType: "uint256", name: "bufferFactor", type: "uint256" },
			{ internalType: "uint256", name: "acceptanceWindow", type: "uint256" },
			{ internalType: "uint16", name: "arbitrationFeeBps", type: "uint16" },
			{ internalType: "uint16", name: "holdBackBps", type: "uint16" },
			{ internalType: "uint64", name: "warrantyPeriod", type: "uint64" },
			{ internalType: "address", name: "token", type: "address" },
			{ internalType: "uint256", name: "tokenAmount", type: "uint256" },
		],
		name: "createContract",
		outputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
		stateMutability: "payable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
		name: "disputeWork",
		outputs: [],
		stateMutability: "payable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "uint256", name: "id", type: "uint256" },
			{ internalType: "uint256", name: "completionPct", type: "uint256" },
		],
		name: "executeRuling",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
		name: "getContract",
		outputs: [
			{
				components: [
					{ internalType: "address", name: "client", type: "address" },
					{ internalType: "uint16", name: "arbitrationFeeBps", type: "uint16" },
					{ internalType: "uint16", name: "holdBackBps", type: "uint16" },
					{ internalType: "enum TrustLedger.Status", name: "status", type: "uint8" },
					{ internalType: "address", name: "freelancer", type: "address" },
					{ internalType: "uint64", name: "warrantyDeadline", type: "uint64" },
					{ internalType: "uint64", name: "projectDeadline", type: "uint64" },
					{ internalType: "uint64", name: "acceptanceWindow", type: "uint64" },
					{ internalType: "uint64", name: "acceptanceDeadline", type: "uint64" },
					{ internalType: "uint64", name: "warrantyPeriod", type: "uint64" },
					{ internalType: "uint256", name: "amount", type: "uint256" },
					{ internalType: "uint256", name: "holdBackAmount", type: "uint256" },
					{ internalType: "uint256", name: "arbitrationId", type: "uint256" },
					{ internalType: "bytes32", name: "contractHash", type: "bytes32" },
					{ internalType: "string", name: "contractURI", type: "string" },
					{ internalType: "bytes32", name: "proofOfWorkHash", type: "bytes32" },
					{ internalType: "string", name: "proofOfWorkURI", type: "string" },
					{ internalType: "address", name: "token", type: "address" },
					{ internalType: "uint256", name: "usdValueAtCreation", type: "uint256" },
					{ internalType: "uint256", name: "previousContractId", type: "uint256" },
				],
				internalType: "struct TrustLedger.EscrowContract",
				name: "",
				type: "tuple",
			},
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "pauser_", type: "address" }],
		name: "initPauser",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "feed_", type: "address" }],
		name: "initPriceFeed",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "registry_", type: "address" }],
		name: "initReputationRegistry",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "uint256", name: "newId", type: "uint256" },
			{ internalType: "uint256", name: "previousId", type: "uint256" },
		],
		name: "linkAmendment",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "nextId",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "pause",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "paused",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "pauser",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "priceFeed",
		outputs: [{ internalType: "contract AggregatorV3Interface", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
		name: "rejectContract",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "reputationRegistry",
		outputs: [{ internalType: "contract IReputationRegistry", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "uint256", name: "id", type: "uint256" },
			{ internalType: "bytes32", name: "powHash", type: "bytes32" },
			{ internalType: "string", name: "powURI", type: "string" },
		],
		name: "submitProofOfWork",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "uint256", name: "id", type: "uint256" },
			{ internalType: "uint8", name: "score", type: "uint8" },
		],
		name: "submitRating",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "unpause",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
] as const;

export const ARBITRATION_ABI = [
	{ inputs: [], name: "AlreadyAppealed", type: "error" },
	{ inputs: [], name: "AlreadyCommitted", type: "error" },
	{ inputs: [], name: "AlreadyRevealed", type: "error" },
	{ inputs: [], name: "AppealWindowElapsed", type: "error" },
	{ inputs: [], name: "AppealWindowNotElapsed", type: "error" },
	{ inputs: [], name: "DisputeNotFinalized", type: "error" },
	{ inputs: [], name: "EthTransferFailed", type: "error" },
	{ inputs: [], name: "InsufficientAppealBond", type: "error" },
	{ inputs: [], name: "InvalidCommitment", type: "error" },
	{ inputs: [], name: "JurorSlotsFilled", type: "error" },
	{ inputs: [], name: "NotAJuror", type: "error" },
	{ inputs: [], name: "NotEligible", type: "error" },
	{ inputs: [], name: "NotInCommitPhase", type: "error" },
	{ inputs: [], name: "NotInRevealPhase", type: "error" },
	{ inputs: [], name: "NotMajority", type: "error" },
	{ inputs: [], name: "NotParty", type: "error" },
	{ inputs: [], name: "PhaseEnded", type: "error" },
	{ inputs: [], name: "PhaseNotEnded", type: "error" },
	{ inputs: [], name: "RewardAlreadyClaimed", type: "error" },
	{
		inputs: [{ internalType: "uint256", name: "disputeId", type: "uint256" }],
		name: "advanceToReveal",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "disputeId", type: "uint256" }],
		name: "appeal",
		outputs: [],
		stateMutability: "payable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "disputeId", type: "uint256" }],
		name: "claimReward",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "uint256", name: "disputeId", type: "uint256" },
			{ internalType: "bytes32", name: "commitment", type: "bytes32" },
		],
		name: "commitVote",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "disputeId", type: "uint256" }],
		name: "executeRuling",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "disputeId", type: "uint256" }],
		name: "finalizeDispute",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "disputeId", type: "uint256" }],
		name: "getDispute",
		outputs: [
			{
				components: [
					{ internalType: "uint256", name: "contractId", type: "uint256" },
					{ internalType: "address", name: "client", type: "address" },
					{ internalType: "uint8", name: "phase", type: "uint8" },
					{ internalType: "bool", name: "finalized", type: "bool" },
					{ internalType: "bool", name: "appealed", type: "bool" },
					{ internalType: "bool", name: "vrfFulfilled", type: "bool" },
					{ internalType: "uint64", name: "phaseDeadline", type: "uint64" },
					{ internalType: "address", name: "freelancer", type: "address" },
					{ internalType: "uint256", name: "contractAmount", type: "uint256" },
					{ internalType: "uint256", name: "feePool", type: "uint256" },
					{ internalType: "uint256", name: "ruling", type: "uint256" },
					{ internalType: "address", name: "appealer", type: "address" },
					{ internalType: "uint256", name: "appealBond", type: "uint256" },
					{ internalType: "uint256", name: "appealDisputeId", type: "uint256" },
					{ internalType: "uint256", name: "parentDisputeId", type: "uint256" },
					{ internalType: "uint256", name: "maxJurors", type: "uint256" },
					{ internalType: "uint256", name: "jurorCount", type: "uint256" },
				],
				internalType: "struct Arbitration.Dispute",
				name: "",
				type: "tuple",
			},
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "disputeId", type: "uint256" }],
		name: "getJurors",
		outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "uint256", name: "disputeId", type: "uint256" },
			{ internalType: "address", name: "juror", type: "address" },
		],
		name: "isMajority",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "nextDisputeId",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "uint256", name: "disputeId", type: "uint256" },
			{ internalType: "uint256", name: "completionPct", type: "uint256" },
			{ internalType: "bytes32", name: "salt", type: "bytes32" },
		],
		name: "revealVote",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
] as const;

export const JUROR_REGISTRY_ABI = [
	{ inputs: [], name: "AlreadyRegistered", type: "error" },
	{ inputs: [], name: "EthTransferFailed", type: "error" },
	{ inputs: [], name: "HasActiveDisputes", type: "error" },
	{ inputs: [], name: "InsufficientStake", type: "error" },
	{ inputs: [], name: "NotRegistered", type: "error" },
	{ inputs: [], name: "StakeBelowMinimum", type: "error" },
	{ inputs: [], name: "StakeLocked", type: "error" },
	{
		inputs: [],
		name: "addStake",
		outputs: [],
		stateMutability: "payable",
		type: "function",
	},
	{
		inputs: [],
		name: "eligibleJurorCount",
		outputs: [{ internalType: "uint256", name: "count", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "juror", type: "address" }],
		name: "getCooldownUntil",
		outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "juror", type: "address" }],
		name: "getJuror",
		outputs: [
			{
				components: [
					{ internalType: "address", name: "addr", type: "address" },
					{ internalType: "bool", name: "active", type: "bool" },
					{ internalType: "uint256", name: "stake", type: "uint256" },
					{ internalType: "uint256", name: "stakeUnlockTime", type: "uint256" },
					{ internalType: "uint256", name: "reputation", type: "uint256" },
					{ internalType: "uint256", name: "disputesParticipated", type: "uint256" },
					{ internalType: "uint256", name: "minorityVotes", type: "uint256" },
					{ internalType: "uint256", name: "activeDisputes", type: "uint256" },
				],
				internalType: "struct IJurorRegistry.JurorInfo",
				name: "",
				type: "tuple",
			},
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "juror", type: "address" }],
		name: "isEligible",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "MIN_STAKE",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "STAKE_LOCK_PERIOD",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "register",
		outputs: [],
		stateMutability: "payable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
		name: "unstake",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
] as const;

export const REPUTATION_REGISTRY_ABI = [
	{
		inputs: [{ internalType: "address", name: "user", type: "address" }],
		name: "averageRating",
		outputs: [
			{ internalType: "uint256", name: "numerator", type: "uint256" },
			{ internalType: "uint256", name: "denominator", type: "uint256" },
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "user", type: "address" }],
		name: "recoveryStatus",
		outputs: [
			{ internalType: "uint256", name: "pending", type: "uint256" },
			{ internalType: "uint256", name: "progress", type: "uint256" },
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "TRUST_LEDGER",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "LOW_RATING_THRESHOLD",
		outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "RECOVERY_CONTRACTS_REQUIRED",
		outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
		stateMutability: "view",
		type: "function",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "address", name: "user", type: "address" },
			{ indexed: true, internalType: "uint8", name: "score", type: "uint8" },
		],
		name: "Rated",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "address", name: "user", type: "address" },
			{ indexed: true, internalType: "uint8", name: "bonus", type: "uint8" },
		],
		name: "RecoveryAchieved",
		type: "event",
	},
] as const;

export const STATUS_LABELS = [
	"Pending",
	"Active",
	"Submitted",
	"Approved",
	"Disputed",
	"Resolved",
	"Cancelled",
] as const;
