/** @type {import("@commitlint/types").UserConfig} */
const config = {
	extends: ["@commitlint/config-conventional"],
	defaultIgnores: true,
	helpUrl: "https://www.conventionalcommits.org/en/v1.0.0/",
	rules: {
		"body-leading-blank": [2, "always"],
		"body-max-line-length": [2, "always", 100],
		"footer-leading-blank": [2, "always"],
		"footer-max-line-length": [2, "always", 100],
		"header-full-stop": [2, "never", "."],
		"header-max-length": [2, "always", 72],
		"scope-case": [2, "always", "kebab-case"],
		"scope-enum": [
			2,
			"always",
			[
				"agents",
				"api",
				"arbitration",
				"ci",
				"contracts",
				"deps",
				"docker",
				"docs",
				"frontend",
				"k8s",
				"logs",
				"security",
				"swc",
				"tests",
				"tooling",
				"types",
				"vercel",
			],
		],
		"subject-case": [2, "always", ["lower-case", "sentence-case"]],
		"subject-empty": [2, "never"],
		"subject-full-stop": [2, "never", "."],
		"type-case": [2, "always", "lower-case"],
		"type-empty": [2, "never"],
		"type-enum": [
			2,
			"always",
			[
				"build",
				"chore",
				"ci",
				"docs",
				"feat",
				"fix",
				"perf",
				"refactor",
				"revert",
				"style",
				"test",
			],
		],
	},
};

export default config;
