"""Minimal Pandas stubs used by analytics generation."""

from collections.abc import Iterable, Iterator
from typing import Literal, TypeAlias, overload

import numpy as np
from numpy.typing import NDArray

Scalar: TypeAlias = str | int | float

class Series:
    def sum(self) -> float: ...
    def isin(self, values: Iterable[object]) -> Series: ...
    def to_numpy(self, dtype: object = ...) -> NDArray[np.float64]: ...
    def max(self) -> float: ...
    def astype(self, dtype: object) -> Series: ...
    def tolist(self) -> list[Scalar]: ...
    def round(self, decimals: int = ...) -> Series: ...
    def __getitem__(self, key: object) -> Scalar: ...
    def __eq__(self, other: object) -> Series: ...  # type: ignore[override]
    def __truediv__(self, other: object) -> Series: ...
    def __mul__(self, other: object) -> Series: ...

class _LocIndexer:
    def __getitem__(self, key: object) -> Series: ...

class DataFrame:
    loc: _LocIndexer

    def __init__(self, data: object = ...) -> None: ...
    @overload
    def __getitem__(self, key: str) -> Series: ...
    @overload
    def __getitem__(self, key: object) -> object: ...
    def iterrows(self) -> Iterator[tuple[object, Series]]: ...
    def assign(self, **kwargs: object) -> DataFrame: ...
    def to_dict(self, orient: Literal["records"] = ...) -> list[dict[str, Scalar]]: ...
