"""Minimal SymPy stubs used by analytics generation."""

class RationalValue:
    def __mul__(self, value: int) -> RationalValue: ...
    def __float__(self) -> float: ...

def Rational(p: int, q: int) -> RationalValue: ...
