// scripts/deploy.ts — Hardhat deployment script (TypeScript/ethers.js equivalent of Deploy.s.sol).
// Run with: npm run hardhat:deploy:sepolia
// This is the Node.js counterpart to contracts/script/Deploy.s.sol.
// It uses ethers.js (via the Hardhat plugin) rather than Foundry's vm cheat codes.

import { ethers } from "hardhat";

async function main(): Promise<void> {
	console.log(process.env.ARBITRUM_SEPOLIA_RPC_URL);
	// ethers.getSigners() returns all accounts configured in hardhat.config.ts for the
	// active network. For arbitrumSepolia, this is the DEPLOYER_PRIVATE_KEY wallet.
	// Destructuring assignment: `[deployer]` picks only the first signer.
	const [deployer] = await ethers.getSigners();
	console.log("Deploying with:", deployer.address);

	// Read the deployer's current nonce (transaction count).
	// Like vm.getNonce() in Foundry — the nonce tells us where the next contracts will land.
	const nonce = await deployer.getNonce();

	// ── Precompute contract addresses ──────────────────────────────────────────
	// On EVM, CREATE opcode addresses are deterministic:
	//   address = keccak256(RLP(deployer, nonce))[12:]
	// ethers.getCreateAddress() computes this without deploying anything.
	// We need this because TrustLedger and JurorRegistry must know Arbitration's
	// address BEFORE it's deployed (all three have immutable cross-references).
	//
	// Deploy order → nonce mapping:
	//   nonce   → JurorRegistry (deployed first)
	//   nonce+1 → TrustLedger  (deployed second)
	//   nonce+2 → Arbitration  (deployed third — address is what we precompute)
	const arbitrationAddr = ethers.getCreateAddress({ from: deployer.address, nonce: nonce + 2 });
	// const trustLedgerAddr = ethers.getCreateAddress({ from: deployer.address, nonce: nonce + 1 });

	// ── Deploy JurorRegistry ───────────────────────────────────────────────────
	// ethers.getContractFactory("JurorRegistry") reads the compiled ABI + bytecode
	// from artifacts/ (generated by `npm run compile`) and creates a factory object.
	const JurorRegistry = await ethers.getContractFactory("JurorRegistry");

	// factory.deploy(...args) sends a CREATE transaction to the network.
	// We pass arbitrationAddr even though Arbitration doesn't exist yet —
	// the constructor just stores it as a plain address.
	const jurorRegistry = await JurorRegistry.deploy(arbitrationAddr);

	// waitForDeployment() waits for the transaction to be mined (included in a block).
	// Without this, the next deploy might use a stale nonce.
	await jurorRegistry.waitForDeployment();
	console.log("JurorRegistry:", await jurorRegistry.getAddress());

	// ── Deploy TrustLedger ────────────────────────────────────────────────────
	const TrustLedger = await ethers.getContractFactory("TrustLedger");
	const trustLedger = await TrustLedger.deploy(arbitrationAddr);
	await trustLedger.waitForDeployment();
	console.log("TrustLedger:  ", await trustLedger.getAddress());

	// ── Deploy Arbitration ────────────────────────────────────────────────────
	// Now that JurorRegistry and TrustLedger exist, we can deploy Arbitration with
	// their real addresses. Arbitration also lands at nonce+2, matching our prediction.
	const Arbitration = await ethers.getContractFactory("Arbitration");
	const arbitration = await Arbitration.deploy(
		await trustLedger.getAddress(),
		await jurorRegistry.getAddress(),
	);
	await arbitration.waitForDeployment();
	console.log("Arbitration:  ", await arbitration.getAddress());

	// ── Verify the address matched our prediction ─────────────────────────────
	// If nonce tracking was off (e.g. a failed tx incremented the nonce), the
	// Arbitration contract would land at the wrong address, breaking JurorRegistry
	// and TrustLedger's immutable references. This check catches that immediately.
	const actualAddr = await arbitration.getAddress();
	if (actualAddr.toLowerCase() !== arbitrationAddr.toLowerCase()) {
		throw new Error(`Address mismatch: expected ${arbitrationAddr}, got ${actualAddr}`);
	}

	console.log("\nDeployment verified successfully!");
	console.log("All contract addresses match precomputed values.");
}

// Standard Node.js async error handling pattern.
// `main()` returns a Promise; `.catch()` handles any thrown error,
// and `process.exit(1)` signals failure to the shell (CI pipelines check this).
main().catch((err: unknown): void => {
	console.error(err);
	process.exit(1);
});
