declare namespace NodeJS {
	interface ProcessEnv {
		NEXT_PUBLIC_TRUSTLEDGER_ADDRESS?: string;
		NEXT_PUBLIC_ARBITRATION_ADDRESS?: string;
		NEXT_PUBLIC_JUROR_REGISTRY_ADDRESS?: string;
		NEXT_PUBLIC_REPUTATION_REGISTRY_ADDRESS?: string;
		NEXT_PUBLIC_TRUSTLEDGER_DEPLOY_BLOCK?: string;
		NEXT_PUBLIC_TRUSTLEDGER_ADDRESS_SEPOLIA?: string;
		NEXT_PUBLIC_ARBITRATION_ADDRESS_SEPOLIA?: string;
		NEXT_PUBLIC_JUROR_REGISTRY_ADDRESS_SEPOLIA?: string;
		NEXT_PUBLIC_REPUTATION_REGISTRY_ADDRESS_SEPOLIA?: string;
		NEXT_PUBLIC_TRUSTLEDGER_DEPLOY_BLOCK_SEPOLIA?: string;
		NEXT_PUBLIC_TRUSTLEDGER_ADDRESS_ARBITRUM?: string;
		NEXT_PUBLIC_ARBITRATION_ADDRESS_ARBITRUM?: string;
		NEXT_PUBLIC_JUROR_REGISTRY_ADDRESS_ARBITRUM?: string;
		NEXT_PUBLIC_REPUTATION_REGISTRY_ADDRESS_ARBITRUM?: string;
		NEXT_PUBLIC_TRUSTLEDGER_DEPLOY_BLOCK_ARBITRUM?: string;
		NEXT_PUBLIC_TRUSTLEDGER_ADDRESS_BASE?: string;
		NEXT_PUBLIC_ARBITRATION_ADDRESS_BASE?: string;
		NEXT_PUBLIC_JUROR_REGISTRY_ADDRESS_BASE?: string;
		NEXT_PUBLIC_REPUTATION_REGISTRY_ADDRESS_BASE?: string;
		NEXT_PUBLIC_TRUSTLEDGER_DEPLOY_BLOCK_BASE?: string;
		NEXT_PUBLIC_TRUSTLEDGER_ADDRESS_OPTIMISM?: string;
		NEXT_PUBLIC_ARBITRATION_ADDRESS_OPTIMISM?: string;
		NEXT_PUBLIC_JUROR_REGISTRY_ADDRESS_OPTIMISM?: string;
		NEXT_PUBLIC_REPUTATION_REGISTRY_ADDRESS_OPTIMISM?: string;
		NEXT_PUBLIC_TRUSTLEDGER_DEPLOY_BLOCK_OPTIMISM?: string;
		NEXT_PUBLIC_USDC_ADDRESS_SEPOLIA?: string;
		NEXT_PUBLIC_USDC_ADDRESS_ARBITRUM?: string;
		NEXT_PUBLIC_USDC_ADDRESS_BASE?: string;
		NEXT_PUBLIC_USDC_ADDRESS_OPTIMISM?: string;
		NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID?: string;
		NEXT_PUBLIC_SITE_URL?: string;
		NEXT_PUBLIC_APP_URL?: string;
		NEXT_PUBLIC_GITHUB_URL?: string;
		NEXT_PUBLIC_PINATA_JWT?: string;
	}
}
