export const TRUSTLEDGER_ABI = [
  {
    inputs: [{ internalType: "address", name: "arbitration_", type: "address" }],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "CompletionPctOutOfRange", type: "error" },
  { inputs: [], name: "DeadlineElapsed", type: "error" },
  { inputs: [], name: "DeadlineNotElapsed", type: "error" },
  { inputs: [], name: "EthTransferFailed", type: "error" },
  { inputs: [], name: "InsufficientFunds", type: "error" },
  { inputs: [], name: "InvalidAcceptanceWindow", type: "error" },
  { inputs: [], name: "InvalidArbitrationFee", type: "error" },
  { inputs: [], name: "InvalidBufferFactor", type: "error" },
  { inputs: [], name: "InvalidHoldBack", type: "error" },
  {
    inputs: [{ internalType: "enum TrustLedger.Status", name: "current", type: "uint8" }],
    name: "InvalidStatus",
    type: "error",
  },
  { inputs: [], name: "InvalidWarrantyPeriod", type: "error" },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  { inputs: [], name: "SelfContract", type: "error" },
  { inputs: [], name: "Unauthorized", type: "error" },
  { inputs: [], name: "WindowElapsed", type: "error" },
  { inputs: [], name: "WindowNotElapsed", type: "error" },
  { inputs: [], name: "ZeroAddress", type: "error" },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "uint256", name: "id", type: "uint256" }],
    name: "ContractAccepted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "uint256", name: "id", type: "uint256" }],
    name: "ContractCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "id", type: "uint256" },
      { indexed: true, internalType: "address", name: "client", type: "address" },
      { indexed: true, internalType: "address", name: "freelancer", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "ContractCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "uint256", name: "id", type: "uint256" }],
    name: "ContractRejected",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "id", type: "uint256" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      { indexed: true, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "FundsReleased",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "id", type: "uint256" },
      { indexed: true, internalType: "bytes32", name: "powHash", type: "bytes32" },
      { indexed: false, internalType: "string", name: "powURI", type: "string" },
    ],
    name: "ProofSubmitted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "id", type: "uint256" },
      { indexed: true, internalType: "uint256", name: "completionPct", type: "uint256" },
    ],
    name: "RulingExecuted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "id", type: "uint256" },
      { indexed: true, internalType: "address", name: "freelancer", type: "address" },
      { indexed: true, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "WarrantyFundsClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "uint256", name: "id", type: "uint256" }],
    name: "WorkApproved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "id", type: "uint256" },
      { indexed: true, internalType: "uint256", name: "arbitrationId", type: "uint256" },
    ],
    name: "WorkDisputed",
    type: "event",
  },
  {
    inputs: [],
    name: "ARBITRATION",
    outputs: [{ internalType: "contract IArbitration", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "BPS_DENOMINATOR",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nextId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "acceptContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "approveWork",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "claimAfterAcceptanceWindow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "claimAfterDeadlineMiss",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "claimWarrantyFunds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "freelancer", type: "address" },
      { internalType: "bytes32", name: "contractHash", type: "bytes32" },
      { internalType: "string", name: "contractURI", type: "string" },
      { internalType: "uint256", name: "estimatedDuration", type: "uint256" },
      { internalType: "uint256", name: "bufferFactor", type: "uint256" },
      { internalType: "uint256", name: "acceptanceWindow", type: "uint256" },
      { internalType: "uint16", name: "arbitrationFeeBps", type: "uint16" },
      { internalType: "uint16", name: "holdBackBps", type: "uint16" },
      { internalType: "uint64", name: "warrantyPeriod", type: "uint64" },
    ],
    name: "createContract",
    outputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "disputeWork",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "getContract",
    outputs: [
      {
        components: [
          { internalType: "address", name: "client", type: "address" },
          { internalType: "uint16", name: "arbitrationFeeBps", type: "uint16" },
          { internalType: "uint16", name: "holdBackBps", type: "uint16" },
          { internalType: "enum TrustLedger.Status", name: "status", type: "uint8" },
          { internalType: "address", name: "freelancer", type: "address" },
          { internalType: "uint64", name: "warrantyDeadline", type: "uint64" },
          { internalType: "uint64", name: "projectDeadline", type: "uint64" },
          { internalType: "uint64", name: "acceptanceWindow", type: "uint64" },
          { internalType: "uint64", name: "acceptanceDeadline", type: "uint64" },
          { internalType: "uint64", name: "warrantyPeriod", type: "uint64" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "uint256", name: "holdBackAmount", type: "uint256" },
          { internalType: "uint256", name: "arbitrationId", type: "uint256" },
          { internalType: "bytes32", name: "contractHash", type: "bytes32" },
          { internalType: "string", name: "contractURI", type: "string" },
          { internalType: "bytes32", name: "proofOfWorkHash", type: "bytes32" },
          { internalType: "string", name: "proofOfWorkURI", type: "string" },
        ],
        internalType: "struct TrustLedger.EscrowContract",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "rejectContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "bytes32", name: "powHash", type: "bytes32" },
      { internalType: "string", name: "powURI", type: "string" },
    ],
    name: "submitProofOfWork",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export const STATUS_LABELS = [
  "Pending",
  "Active",
  "Submitted",
  "Approved",
  "Disputed",
  "Resolved",
  "Cancelled",
] as const;
